"use client";
import "./globals.css";
import NextProviders from "../providers/provider";

export const metadata = {
  title: "School Alumni",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextProviders>{children}</NextProviders>
      </body>
    </html>
  );
}
